version: 0.2

env:
  variables:
    FUNCTION_NAME: doorDashProcessor
    REGION: ap-south-1

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t package/
  build:
    commands:
      - echo "Building deployment package..."
      - cp -r lambda_function.py package/
      - cd package
      - zip -r ../deployment_package.zip .
      - cd ..
      - echo "Deployment package created successfully."
  post_build:
    commands:
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://deployment_package.zip --region $REGION
      - echo "Lambda updated successfully."

artifacts:
  files:
    - deployment_package.zip
